import { TimeZone } from '../types';

export const timeZoneOptions = [
  { value: { id: 'UTC', name: 'Etc/UTC', offset: 0, abbreviation: 'UTC' }, label: 'UTC' },
  { value: { id: 'America/New_York', name: 'America/New_York', offset: -5, abbreviation: 'EST' }, label: 'New York' },
  { value: { id: 'America/Chicago', name: 'America/Chicago', offset: -6, abbreviation: 'CST' }, label: 'Chicago' },
  { value: { id: 'America/Denver', name: 'America/Denver', offset: -7, abbreviation: 'MST' }, label: 'Denver' },
  { value: { id: 'America/Los_Angeles', name: 'America/Los_Angeles', offset: -8, abbreviation: 'PST' }, label: 'Los Angeles' },
  { value: { id: 'America/Anchorage', name: 'America/Anchorage', offset: -9, abbreviation: 'AKST' }, label: 'Anchorage' },
  { value: { id: 'Pacific/Honolulu', name: 'Pacific/Honolulu', offset: -10, abbreviation: 'HST' }, label: 'Honolulu' },
  { value: { id: 'Europe/London', name: 'Europe/London', offset: 0, abbreviation: 'GMT' }, label: 'London' },
  { value: { id: 'Europe/Berlin', name: 'Europe/Berlin', offset: 1, abbreviation: 'CET' }, label: 'Berlin' },
  { value: { id: 'Europe/Paris', name: 'Europe/Paris', offset: 1, abbreviation: 'CET' }, label: 'Paris' },
  { value: { id: 'Europe/Rome', name: 'Europe/Rome', offset: 1, abbreviation: 'CET' }, label: 'Rome' },
  { value: { id: 'Europe/Madrid', name: 'Europe/Madrid', offset: 1, abbreviation: 'CET' }, label: 'Madrid' },
  { value: { id: 'Europe/Amsterdam', name: 'Europe/Amsterdam', offset: 1, abbreviation: 'CET' }, label: 'Amsterdam' },
  { value: { id: 'Europe/Athens', name: 'Europe/Athens', offset: 2, abbreviation: 'EET' }, label: 'Athens' },
  { value: { id: 'Europe/Moscow', name: 'Europe/Moscow', offset: 3, abbreviation: 'MSK' }, label: 'Moscow' },
  { value: { id: 'Asia/Dubai', name: 'Asia/Dubai', offset: 4, abbreviation: 'GST' }, label: 'Dubai' },
  { value: { id: 'Asia/Kolkata', name: 'Asia/Kolkata', offset: 5.5, abbreviation: 'IST' }, label: 'Mumbai/Delhi' },
  { value: { id: 'Asia/Bangkok', name: 'Asia/Bangkok', offset: 7, abbreviation: 'ICT' }, label: 'Bangkok' },
  { value: { id: 'Asia/Singapore', name: 'Asia/Singapore', offset: 8, abbreviation: 'SGT' }, label: 'Singapore' },
  { value: { id: 'Asia/Shanghai', name: 'Asia/Shanghai', offset: 8, abbreviation: 'CST' }, label: 'Shanghai/Beijing' },
  { value: { id: 'Asia/Tokyo', name: 'Asia/Tokyo', offset: 9, abbreviation: 'JST' }, label: 'Tokyo' },
  { value: { id: 'Asia/Seoul', name: 'Asia/Seoul', offset: 9, abbreviation: 'KST' }, label: 'Seoul' },
  { value: { id: 'Australia/Sydney', name: 'Australia/Sydney', offset: 11, abbreviation: 'AEDT' }, label: 'Sydney' },
  { value: { id: 'Australia/Melbourne', name: 'Australia/Melbourne', offset: 11, abbreviation: 'AEDT' }, label: 'Melbourne' },
  { value: { id: 'Pacific/Auckland', name: 'Pacific/Auckland', offset: 13, abbreviation: 'NZDT' }, label: 'Auckland' },
  { value: { id: 'America/Sao_Paulo', name: 'America/Sao_Paulo', offset: -3, abbreviation: 'BRT' }, label: 'São Paulo' },
  { value: { id: 'America/Toronto', name: 'America/Toronto', offset: -5, abbreviation: 'EST' }, label: 'Toronto' },
  { value: { id: 'America/Vancouver', name: 'America/Vancouver', offset: -8, abbreviation: 'PST' }, label: 'Vancouver' },
  { value: { id: 'Africa/Cairo', name: 'Africa/Cairo', offset: 2, abbreviation: 'EET' }, label: 'Cairo' },
  { value: { id: 'Africa/Johannesburg', name: 'Africa/Johannesburg', offset: 2, abbreviation: 'SAST' }, label: 'Johannesburg' },
];